name: umur
version: 10.0.0+10
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  age_calculator: ^1.0.0
  cupertino_icons: ^1.0.2
  dropdown_search: ^4.0.1
  expansion_tile_card: ^2.0.0
  flutter:
    sdk: flutter
  flutter_slidable: ^1.3.0
  get: 4.6.5
  google_fonts: ^3.0.1
  google_mobile_ads: ^1.2.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  lottie: ^1.3.0
  rename: ^2.0.1
  simple_animations: ^4.0.1
  supercharged: ^2.1.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#005555"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  assets:
    - assets/
  uses-material-design: true
